USE DiningDucks;

-- USER

INSERT INTO User(name, email, role) VALUES ('Georgeanna Want','gwant0@reference.com','employee');
INSERT INTO User(name, email, role) VALUES ('Elianora Overlow','eoverlow1@bravesites.com','company');
INSERT INTO User(name, email, role) VALUES ('Bink Reams','breams2@wiley.com','employee');
INSERT INTO User(name, email, role) VALUES ('Gerladina Marrian','gmarrian3@fotki.com','employee');
INSERT INTO User(name, email, role) VALUES ('Grover Coatts','gcoatts4@merriam-webster.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Ame Khoter','akhoter5@soup.io','employee');
INSERT INTO User(name, email, role) VALUES ('Rebekkah Poppy','rpoppy6@plala.or.jp','employee');
INSERT INTO User(name, email, role) VALUES ('Correna Kondrat','ckondrat7@elegantthemes.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Lexi Blaisdell','lblaisdell8@technorati.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Fabe Grimsdith','fgrimsdith9@google.es','reviewer');
INSERT INTO User(name, email, role) VALUES ('Valry Livings','vlivingsa@ftc.gov','admin');
INSERT INTO User(name, email, role) VALUES ('Alexia O'' Culligan','aob@youtube.com','admin');
INSERT INTO User(name, email, role) VALUES ('Falito Hext','fhextc@eepurl.com','company');
INSERT INTO User(name, email, role) VALUES ('Randa Sprasen','rsprasend@abc.net.au','reviewer');
INSERT INTO User(name, email, role) VALUES ('Philippa Welchman','pwelchmane@altervista.org','reviewer');
INSERT INTO User(name, email, role) VALUES ('Don Worner','dwornerf@slashdot.org','reviewer');
INSERT INTO User(name, email, role) VALUES ('Glenn Lightfoot','glightfootg@360.cn','reviewer');
INSERT INTO User(name, email, role) VALUES ('Etienne Thicking','ethickingh@ebay.co.uk','reviewer');
INSERT INTO User(name, email, role) VALUES ('Catlaina Salvador','csalvadori@utexas.edu','company');
INSERT INTO User(name, email, role) VALUES ('Charisse Delong','cdelongj@stumbleupon.com','admin');
INSERT INTO User(name, email, role) VALUES ('Harlene Cain','hcaink@pinterest.com','company');
INSERT INTO User(name, email, role) VALUES ('Gloria Eicheler','geichelerl@goodreads.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('April Dumbrall','adumbrallm@intel.com','employee');
INSERT INTO User(name, email, role) VALUES ('Gilly Shivlin','gshivlinn@yale.edu','reviewer');
INSERT INTO User(name, email, role) VALUES ('Deb Aiton','daitono@cnn.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Susanne Normabell','snormabellp@issuu.com','employee');
INSERT INTO User(name, email, role) VALUES ('Otha Nettleship','onettleshipq@surveymonkey.com','employee');
INSERT INTO User(name, email, role) VALUES ('Neila Haselup','nhaselupr@soup.io','employee');
INSERT INTO User(name, email, role) VALUES ('Marni Stiff','mstiffs@altervista.org','reviewer');
INSERT INTO User(name, email, role) VALUES ('Arman Chatres','achatrest@unc.edu','admin');
INSERT INTO User(name, email, role) VALUES ('Christoph Yarmouth','cyarmouthu@github.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Lesly Hinz','lhinzv@bandcamp.com','admin');
INSERT INTO User(name, email, role) VALUES ('Jerome Lohan','jlohanw@newyorker.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Jacqui Lapthorne','jlapthornex@discovery.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Jeane Pays','jpaysy@posterous.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Taddeusz Garmon','tgarmonz@cdbaby.com','employee');
INSERT INTO User(name, email, role) VALUES ('Leonanie Steggles','lsteggles10@over-blog.com','admin');
INSERT INTO User(name, email, role) VALUES ('Petunia Bethell','pbethell11@dyndns.org','admin');
INSERT INTO User(name, email, role) VALUES ('Lona Sadat','lsadat12@huffingtonpost.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Deanna Rowcastle','drowcastle13@wisc.edu','company');
-- COMPANY

INSERT INTO Company(name) VALUES ('Midtown Bites');
INSERT INTO Company(name) VALUES ('Lighthouse Dining');
INSERT INTO Company(name) VALUES ('Oak Table');
INSERT INTO Company(name) VALUES ('Riverstone Dining');
INSERT INTO Company(name) VALUES ('Skyline Kitchen');
INSERT INTO Company(name) VALUES ('Maple & Main');
INSERT INTO Company(name) VALUES ('Morning Star Cafe');
INSERT INTO Company(name) VALUES ('Cedar Plate');
INSERT INTO Company(name) VALUES ('Amber Table');
INSERT INTO Company(name) VALUES ('Summit Table');
INSERT INTO Company(name) VALUES ('Stonebridge Grill');
INSERT INTO Company(name) VALUES ('Willow & Fork');
INSERT INTO Company(name) VALUES ('West End Grill');
INSERT INTO Company(name) VALUES ('Brick Oven House');
INSERT INTO Company(name) VALUES ('Urban Bite');
INSERT INTO Company(name) VALUES ('Coastal Spoon');
INSERT INTO Company(name) VALUES ('Cornerstone Cafe');
INSERT INTO Company(name) VALUES ('Lighthouse Dining');
INSERT INTO Company(name) VALUES ('Ironwood Kitchen');
INSERT INTO Company(name) VALUES ('Urban Bite');
INSERT INTO Company(name) VALUES ('Skyline Kitchen');
INSERT INTO Company(name) VALUES ('Eastwood Eats');
INSERT INTO Company(name) VALUES ('Crimson Fork');
INSERT INTO Company(name) VALUES ('Northwind Diner');
INSERT INTO Company(name) VALUES ('Oak Table');
INSERT INTO Company(name) VALUES ('Ironwood Kitchen');
INSERT INTO Company(name) VALUES ('Urban Bite');
INSERT INTO Company(name) VALUES ('Golden Hour Bistro');
INSERT INTO Company(name) VALUES ('Blue Harbor Grill');
INSERT INTO Company(name) VALUES ('Brick Oven House');
INSERT INTO Company(name) VALUES ('Dining Ducks');
INSERT INTO Company(name) VALUES ('Golden Fork');
INSERT INTO Company(name) VALUES ('Maple & Main');
INSERT INTO Company(name) VALUES ('Cornerstone Cafe');
INSERT INTO Company(name) VALUES ('Blue Harbor Grill');
INSERT INTO Company(name) VALUES ('Bluebird Dining');
INSERT INTO Company(name) VALUES ('Harbor & Hearth');
INSERT INTO Company(name) VALUES ('Velvet Plate');
INSERT INTO Company(name) VALUES ('Lighthouse Dining');
INSERT INTO Company(name) VALUES ('Harvest & Co');

-- RESTAURANT LOCATION

INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (13,'69916 Dixon Road','Santa Rosa de Lima','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (2,'3 Kings Plaza','Sarae','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (28,'9520 Cody Junction','Selouane','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (2,'17186 Leroy Point','Säffle','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (23,'61780 Myrtle Plaza','San Juan Ixcoy','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'7921 Homewood Alley','Ubon Ratchathani','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (22,'827 Vahlen Place','Göteborg','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (30,'21933 Dunning Street','Santo Domingo','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (21,'9 Norway Maple Drive','Boavista','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (9,'52897 Huxley Park','Матејче','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (4,'332 Ridgeview Court','Annecy','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (10,'6266 Granby Parkway','Jiefang','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (26,'25 Alpine Circle','Jazovo','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (13,'28250 Haas Terrace','San Carlos','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'85131 Spaight Street','Donja Mahala','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (27,'852 Evergreen Way','Zuoxi','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (7,'2 Division Place','Rustāq','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (16,'8282 Carey Place','Skoroszyce','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'6 Lunder Point','Huurch','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'991 Forest Drive','Jiangcun','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'39884 Prairieview Court','Paris 12','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (40,'27 Mayer Street','São João Nepomuceno','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (31,'21 Atwood Pass','Casa Branca','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'8 Starling Drive','Asprángeloi','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (5,'7834 Elmside Court','Luchingu','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'6766 Porter Place','Sale','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (16,'95108 Barby Drive','Kedungasem','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (7,'55722 Cherokee Avenue','Kaduseeng','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'45 Old Shore Trail','Jinshan','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (25,'58028 Carpenter Alley','Pirassununga','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'235 Express Place','Bcharré','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (23,'9307 Hollow Ridge Place','Pecka','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (34,'4 Arizona Avenue','Olyka','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (32,'0397 Shoshone Point','Łąka Prudnicka','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'08562 Holmberg Circle','Trairi','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'631 Harbort Lane','Garzón','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (4,'6 Bayside Way','Zhangjiafang','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'2 Burrows Crossing','Alfeizerão','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (1,'76 Harbort Hill','El Nido','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'411 Old Shore Pass','Tengah','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'0 Pawling Trail','Houmt Souk','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'6881 Bartelt Junction','Norak','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (39,'5 Reindahl Drive','Yaosai','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'7427 East Alley','Okanagan','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (27,'223 Oak Terrace','Desa Baregbeg','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'7692 Sommers Crossing','Shawnee Mission','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'66 Sage Trail','Bintang','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'664 Goodland Park','Cidahu','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (23,'0708 Melrose Terrace','Strogino','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'5 Northport Alley','Xiongchi','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (8,'84813 Mayfield Park','Kamárai','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (35,'42140 Clyde Gallagher Avenue','Kudusan','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (1,'7005 Cody Parkway','Pangalangan','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (16,'68 Cambridge Place','Wenshao','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (34,'758 Merchant Junction','Menzel Abderhaman','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (10,'9 Lyons Hill','Beishan','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (30,'3027 Bunker Hill Trail','Lagunas','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (25,'1510 Sauthoff Crossing','Nerópolis','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'0469 Superior Street','Bečmen','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (30,'304 Fairfield Point','Velventós','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (4,'79381 Gulseth Point','Nuevo Arraiján','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (1,'54649 School Trail','Baisha','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (36,'8672 Nancy Drive','Ōkuchi','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (14,'270 Laurel Circle','Kabar Utara','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (22,'13 Holmberg Plaza','Lobuni','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (36,'0 Eagle Crest Trail','Marigot','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (33,'07583 5th Circle','Tirtopuro','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (10,'37965 Tomscot Drive','Rezh','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (40,'046 Tony Pass','Dolna Banya','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (17,'810 Brickson Park Avenue','Pescadería','$$$');

-- CATEGORY (food, service, etc.)

INSERT INTO Category(name) VALUES ('pay');
INSERT INTO Category(name) VALUES ('management');
INSERT INTO Category(name) VALUES ('work-life balance');
INSERT INTO Category(name) VALUES ('oveall');
INSERT INTO Category(name) VALUES ('food');
INSERT INTO Category(name) VALUES ('$$$');
INSERT INTO Category(name) VALUES ('service');

-- CUSTOMER REVIEW

INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-6527','Checchi','The ambiance was fantastic.','3/9/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-3898','Brookhouse','food was mediocre.','11/1/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2322','Battaille','Not worth the price','5/24/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4049','Janoschek','The ambiance was fantastic.','3/25/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9368','Brand-Hardy','Great food and service!','10/19/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-5714','Cayley','Great food and service!','7/29/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7551','Ramble','The ambiance was fantastic.','5/29/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-8050','Van Arsdalen','food was mediocre.','11/10/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7132','Moquin','Not worth the price','12/27/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4868','Ratt','Would definitely recommend this place!','6/14/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7538','Peotz','Great food and service!','9/11/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7396','Sterry','The ambiance was fantastic.','3/2/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-3779','Gloyens','food was mediocre.','10/31/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7040','Valenti','Not worth the price','12/11/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9890','Romain','food was mediocre.','5/25/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-3702','Leyfield','Not worth the price','3/30/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2469','Clamp','food was mediocre.','9/26/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-0348','Rosita','Great food and service!','9/20/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7006','Dehm','food was mediocre.','4/16/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4201','Tookey','food was mediocre.','5/16/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7719','Scamaden','Not worth the price','12/12/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-8454','Ahern','Great food and service!','6/11/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4125','Boughtflower','Great food and service!','3/3/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2710','Bradtke','food was mediocre.','5/31/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-3979','Brombell','food was mediocre.','8/31/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2177','Basden','The ambiance was fantastic.','12/31/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4552','Croizier','Great food and service!','7/18/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7658','Philimore','Great food and service!','6/20/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7743','Gaylord','The ambiance was fantastic.','3/31/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1613','Rowston','Would definitely recommend this place!','4/14/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-8010','Kareman','The ambiance was fantastic.','3/28/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1601','Pringuer','The ambiance was fantastic.','6/13/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1931','Caurah','food was mediocre.','11/10/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-0372','Padly','Great food and service!','6/6/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1625','Latter','The ambiance was fantastic.','3/26/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9966','Orrin','Not worth the price','3/21/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2560','Quaif','food was mediocre.','7/21/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-6347','Scammonden','Great food and service!','10/3/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-3787','Jaggers','food was mediocre.','1/25/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-8964','Eby','Would definitely recommend this place!','8/31/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-8166','Adamoli','Would definitely recommend this place!','5/11/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-0938','Braunstein','Great food and service!','12/25/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-0543','Elphinstone','Great food and service!','3/10/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-8463','Mingay','The ambiance was fantastic.','7/27/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1233','Amburgy','Not worth the price','5/16/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-0259','Dubber','Not worth the price','5/4/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-8442','Sullly','food was mediocre.','4/15/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9248','Kyneton','Would definitely recommend this place!','9/1/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-6240','Burrel','Not worth the price','12/26/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9901','Niblock','Great food and service!','1/16/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2544','Tolman','The ambiance was fantastic.','6/3/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-0906','McGarrie','The ambiance was fantastic.','3/15/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9730','Lusk','Would definitely recommend this place!','8/25/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-7732','Tathacott','food was mediocre.','8/23/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4540','Pine','Great food and service!','10/28/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-5524','Capozzi','Great food and service!','8/5/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-5082','Kristoffersson','Not worth the price','5/20/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-3541','Stych','food was mediocre.','9/10/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9169','Crouse','Not worth the price','7/9/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4669','Kerswell','Great food and service!','1/12/2026');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2172','Bennion','food was mediocre.','4/2/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2827','Swiffin','Great food and service!','3/18/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1875','Jennions','Would definitely recommend this place!','12/27/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1277','Hegg','The ambiance was fantastic.','12/25/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-4345','Stocking','Great food and service!','10/19/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-0975','Wylam','The ambiance was fantastic.','4/6/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-2891','Cicccitti','Great food and service!','8/2/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9447','Sieb','Not worth the price','6/30/2025');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-9305','Britian','Not worth the price','6/10/2024');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES ('USR-1655','Siflet','The ambiance was fantastic.','12/9/2024');

-- REVIEW RATINGS (per category)

INSERT INTO Rating(review_id,category_id,score) VALUES (57,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (2,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (5,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (21,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (10,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (26,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (53,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (44,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (43,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (15,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (65,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (35,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (7,4,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,5,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (42,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (42,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (12,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (59,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (36,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (49,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,2,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (47,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (57,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (45,3,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (8,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,7,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (42,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (57,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (33,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (16,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,4,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (5,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (38,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (66,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (6,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (26,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (39,3,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (2,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (43,1,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (5,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (21,2,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (11,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (53,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (4,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (32,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,4,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (38,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (64,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (15,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (51,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,4,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (25,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,1,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (51,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (14,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,7,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,3,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (16,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (32,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (53,4,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (49,3,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (21,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (59,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (66,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (63,4,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (28,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (15,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (64,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (29,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (24,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (63,3,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (6,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (67,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (33,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (2,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (50,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (36,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (54,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (67,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (46,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (27,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (43,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (48,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (12,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (11,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (10,1,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (13,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (40,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (32,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (60,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (50,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (12,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (18,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (26,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (64,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (59,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,5,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (14,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (38,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (60,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (58,4,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (35,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (44,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,2,2);

-- EMPLOYEE REVIEW

INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (22,10,'making my job easier.','2/12/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (1,15,'The customers were patient and understanding','9/2/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,54,'The customers were patient and understanding','9/1/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,55,'I had a great time interacting with the customers and providing top-notch service.','10/1/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (9,12,'The atmosphere was cozy and welcoming.','7/25/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,10,'The food was delicious and the customers were very friendly.','9/19/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,20,'The restaurant was busy but I managed to keep up with all the orders and requests.','3/30/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,5,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','6/10/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (28,37,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','3/18/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,28,'I had a great time interacting with the customers and providing top-notch service.','3/21/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,70,'I had a great time interacting with the customers and providing top-notch service.','1/24/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (11,29,'The food was delicious and the customers were very friendly.','9/11/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (14,26,'I had a great time interacting with the customers and providing top-notch service.','9/4/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (29,24,'I received positive feedback from the customers about the food and service.','6/20/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,22,'The atmosphere was cozy and welcoming.','5/5/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (31,28,'The restaurant was busy but I managed to keep up with all the orders and requests.','11/25/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (37,51,'The customers were patient and understanding','3/18/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (29,59,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','10/30/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (32,7,'I received positive feedback from the customers about the food and service.','9/3/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (26,68,'I received positive feedback from the customers about the food and service.','2/18/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,19,'The service was excellent and the customers seemed to enjoy their meals.','2/6/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,8,'The atmosphere was cozy and welcoming.','8/19/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (21,11,'making my job easier.','3/2/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (28,47,'The customers were patient and understanding','12/15/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,31,'I had a great time interacting with the customers and providing top-notch service.','3/11/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,47,'The food was delicious and the customers were very friendly.','1/23/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (23,24,'I felt proud of the quality of service I was able to deliver to the customers.','11/9/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,32,'The service was excellent and the customers seemed to enjoy their meals.','5/22/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (7,52,'I felt proud of the quality of service I was able to deliver to the customers.','3/28/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,26,'The service was excellent and the customers seemed to enjoy their meals.','5/6/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,27,'The customers were appreciative of the recommendations I provided for their meals.','3/9/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,56,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','6/4/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,18,'I felt proud of the quality of service I was able to deliver to the customers.','8/19/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,53,'I felt proud of the quality of service I was able to deliver to the customers.','7/2/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,65,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','10/9/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (16,43,'The service was excellent and the customers seemed to enjoy their meals.','6/4/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (15,21,'I had a great time interacting with the customers and providing top-notch service.','12/6/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (23,11,'The atmosphere was cozy and welcoming.','8/4/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,51,'making my job easier.','5/16/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,13,'I felt proud of the quality of service I was able to deliver to the customers.','7/14/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (27,40,'The service was excellent and the customers seemed to enjoy their meals.','1/28/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (14,55,'The atmosphere was cozy and welcoming.','12/15/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (5,7,'I felt proud of the quality of service I was able to deliver to the customers.','1/14/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (32,6,'making my job easier.','1/10/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (7,33,'I had a great time interacting with the customers and providing top-notch service.','12/14/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (1,44,'The customers were patient and understanding','4/6/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (24,70,'I received positive feedback from the customers about the food and service.','3/21/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (26,43,'I received positive feedback from the customers about the food and service.','8/9/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,38,'The customers were appreciative of the recommendations I provided for their meals.','1/28/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,46,'The restaurant was busy but I managed to keep up with all the orders and requests.','8/8/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,70,'The restaurant was busy but I managed to keep up with all the orders and requests.','5/21/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (24,20,'The service was excellent and the customers seemed to enjoy their meals.','11/27/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (12,57,'The customers were patient and understanding','12/1/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (5,30,'The atmosphere was cozy and welcoming.','12/8/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (4,61,'I received positive feedback from the customers about the food and service.','5/30/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,63,'The customers were patient and understanding','10/15/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (15,49,'The customers were patient and understanding','2/14/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (1,15,'The service was excellent and the customers seemed to enjoy their meals.','7/22/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,45,'The restaurant was busy but I managed to keep up with all the orders and requests.','8/31/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,5,'The customers were patient and understanding','7/1/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,47,'The atmosphere was cozy and welcoming.','12/21/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (16,15,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','6/13/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,5,'The atmosphere was cozy and welcoming.','1/7/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,25,'The atmosphere was cozy and welcoming.','2/16/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (13,59,'The service was excellent and the customers seemed to enjoy their meals.','2/17/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,32,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','3/9/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,27,'The customers were patient and understanding','12/18/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (22,53,'The restaurant was busy but I managed to keep up with all the orders and requests.','3/22/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,47,'making my job easier.','1/24/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,29,'I received positive feedback from the customers about the food and service.','7/19/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (13,66,'The atmosphere was cozy and welcoming.','2/2/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,31,'I received positive feedback from the customers about the food and service.','3/21/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,61,'I had a great time interacting with the customers and providing top-notch service.','3/30/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,24,'I felt proud of the quality of service I was able to deliver to the customers.','11/8/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,21,'I felt proud of the quality of service I was able to deliver to the customers.','8/29/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (5,13,'I received positive feedback from the customers about the food and service.','5/27/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,5,'making my job easier.','9/17/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,66,'The atmosphere was cozy and welcoming.','12/28/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (21,17,'The customers were patient and understanding','3/6/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,27,'making my job easier.','12/11/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (26,40,'I felt proud of the quality of service I was able to deliver to the customers.','3/9/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (25,46,'making my job easier.','7/24/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,33,'The atmosphere was cozy and welcoming.','3/16/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,42,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','1/9/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (27,36,'The customers were appreciative of the recommendations I provided for their meals.','6/11/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (13,22,'I had a great time interacting with the customers and providing top-notch service.','1/6/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,18,'The customers were appreciative of the recommendations I provided for their meals.','11/3/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,22,'I received positive feedback from the customers about the food and service.','2/27/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,46,'making my job easier.','1/5/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,18,'The food was delicious and the customers were very friendly.','11/8/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (3,49,'I received positive feedback from the customers about the food and service.','6/26/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (11,38,'making my job easier.','4/1/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (11,36,'The atmosphere was cozy and welcoming.','2/1/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,9,'I had a great time interacting with the customers and providing top-notch service.','2/11/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,61,'I felt proud of the quality of service I was able to deliver to the customers.','9/28/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,66,'I received positive feedback from the customers about the food and service.','5/6/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (25,54,'The customers were appreciative of the recommendations I provided for their meals.','3/13/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,2,'I received positive feedback from the customers about the food and service.','1/12/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,58,'making my job easier.','3/11/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (25,37,'The customers were patient and understanding','8/26/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (6,9,'The customers were appreciative of the recommendations I provided for their meals.','5/22/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (37,4,'making my job easier.','3/22/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,26,'The customers were patient and understanding','8/7/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,52,'I received positive feedback from the customers about the food and service.','4/19/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (23,7,'The customers were patient and understanding','1/1/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,31,'I felt proud of the quality of service I was able to deliver to the customers.','4/10/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (15,54,'making my job easier.','12/16/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (16,10,'The restaurant was busy but I managed to keep up with all the orders and requests.','12/8/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,69,'The service was excellent and the customers seemed to enjoy their meals.','8/26/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,54,'I had a great time interacting with the customers and providing top-notch service.','11/2/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (37,10,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','8/12/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (32,11,'making my job easier.','11/7/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (24,15,'I received positive feedback from the customers about the food and service.','9/10/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,23,'making my job easier.','7/10/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,51,'I felt proud of the quality of service I was able to deliver to the customers.','9/5/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,11,'The customers were appreciative of the recommendations I provided for their meals.','11/29/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,4,'The atmosphere was cozy and welcoming.','4/22/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (3,13,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','10/18/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,12,'The service was excellent and the customers seemed to enjoy their meals.','8/22/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,50,'The customers were appreciative of the recommendations I provided for their meals.','11/10/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (6,28,'The restaurant was busy but I managed to keep up with all the orders and requests.','12/28/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (22,50,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','10/22/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (29,62,'The atmosphere was cozy and welcoming.','9/23/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,45,'I felt proud of the quality of service I was able to deliver to the customers.','1/23/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (39,65,'The food was delicious and the customers were very friendly.','4/1/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (39,13,'The customers were appreciative of the recommendations I provided for their meals.','7/11/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,67,'The food was delicious and the customers were very friendly.','2/2/2026');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (12,25,'The customers were appreciative of the recommendations I provided for their meals.','12/20/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,47,'I had a great time interacting with the customers and providing top-notch service.','11/19/2025');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (7,16,'I received positive feedback from the customers about the food and service.','6/15/2025');

-- EMPLOYEE RATINGS

INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (833,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (839,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (77,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (662,6,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (191,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (77,6,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (397,7,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (285,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (741,4,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (334,4,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (96,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (328,7,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (3,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (603,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (187,3,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (551,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (170,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (472,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (252,5,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (280,1,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (345,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (516,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (871,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (358,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (24,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (325,3,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (269,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (694,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (4,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (728,7,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (582,1,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (398,4,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (711,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (496,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (427,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (106,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (868,7,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (35,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (444,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (44,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (714,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (212,2,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (946,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (767,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (804,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (23,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (216,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (286,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (591,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (663,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (331,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (568,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (578,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (394,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (997,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (559,6,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (452,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (5,3,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (656,7,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (599,3,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (454,3,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (796,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (367,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (768,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (758,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (410,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (480,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (425,5,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (71,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (216,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (646,3,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (707,5,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (144,4,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (898,4,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (69,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (591,2,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (722,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (867,7,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (17,6,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (53,6,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (782,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (881,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (53,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (59,3,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (893,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (908,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (321,5,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (750,1,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (132,5,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (295,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (561,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (527,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (898,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (110,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (164,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (759,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (792,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (129,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (309,4,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (770,3,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (680,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (910,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (134,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (116,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (594,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (347,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (948,7,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (344,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (819,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (998,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (768,7,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (511,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (519,7,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (555,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (804,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (992,3,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (333,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (304,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (489,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (480,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (412,6,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (67,7,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (366,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (431,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (912,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (51,3,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (490,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (511,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (826,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (284,6,2);

-- PHOTOS

INSERT INTO Photo(location_id,url) VALUES (16,'http://dummyimage.com/225x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/131x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (18,'http://dummyimage.com/146x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (63,'http://dummyimage.com/179x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (46,'http://dummyimage.com/138x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (20,'http://dummyimage.com/220x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/238x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (57,'http://dummyimage.com/241x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (59,'http://dummyimage.com/212x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (40,'http://dummyimage.com/136x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (2,'http://dummyimage.com/207x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (17,'http://dummyimage.com/207x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (5,'http://dummyimage.com/153x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/148x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (62,'http://dummyimage.com/208x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (10,'http://dummyimage.com/189x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (31,'http://dummyimage.com/107x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (59,'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (29,'http://dummyimage.com/102x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (45,'http://dummyimage.com/218x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (51,'http://dummyimage.com/197x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (29,'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (1,'http://dummyimage.com/223x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (43,'http://dummyimage.com/204x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (70,'http://dummyimage.com/198x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (43,'http://dummyimage.com/212x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (27,'http://dummyimage.com/183x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (26,'http://dummyimage.com/172x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (63,'http://dummyimage.com/127x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (42,'http://dummyimage.com/197x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (27,'http://dummyimage.com/192x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/134x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (42,'http://dummyimage.com/120x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (48,'http://dummyimage.com/186x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (46,'http://dummyimage.com/234x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (43,'http://dummyimage.com/121x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (63,'http://dummyimage.com/173x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (14,'http://dummyimage.com/179x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (17,'http://dummyimage.com/139x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (25,'http://dummyimage.com/129x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (53,'http://dummyimage.com/138x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (26,'http://dummyimage.com/155x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (36,'http://dummyimage.com/233x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (57,'http://dummyimage.com/226x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (38,'http://dummyimage.com/192x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (15,'http://dummyimage.com/227x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (35,'http://dummyimage.com/242x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (57,'http://dummyimage.com/160x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (6,'http://dummyimage.com/162x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (13,'http://dummyimage.com/112x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (1,'http://dummyimage.com/222x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (23,'http://dummyimage.com/149x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (4,'http://dummyimage.com/204x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (49,'http://dummyimage.com/134x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (9,'http://dummyimage.com/226x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (64,'http://dummyimage.com/237x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (44,'http://dummyimage.com/248x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (47,'http://dummyimage.com/123x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (51,'http://dummyimage.com/107x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (45,'http://dummyimage.com/164x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (44,'http://dummyimage.com/154x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (62,'http://dummyimage.com/198x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (62,'http://dummyimage.com/190x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (12,'http://dummyimage.com/101x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (3,'http://dummyimage.com/107x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (4,'http://dummyimage.com/140x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (42,'http://dummyimage.com/123x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (13,'http://dummyimage.com/215x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (28,'http://dummyimage.com/146x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (15,'http://dummyimage.com/242x100.png/cc0000/ffffff');

-- COMPLAINTS (For admin, help desk)

INSERT INTO Complaint(user_id,description,status) VALUES (13,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (11,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (33,'slow loading times','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (32,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (23,'poor customer service','open');
INSERT INTO Complaint(user_id,description,status) VALUES (9,'poor quality products','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (5,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (6,'poor quality products','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (36,'incorrect product descriptions','open');
INSERT INTO Complaint(user_id,description,status) VALUES (24,'poor quality products','open');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'website crashes','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (27,'poor quality products','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'poor customer service','open');
INSERT INTO Complaint(user_id,description,status) VALUES (11,'website crashes','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (24,'unresponsive support','open');
INSERT INTO Complaint(user_id,description,status) VALUES (22,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (1,'poor customer service','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (16,'slow loading times','open');
INSERT INTO Complaint(user_id,description,status) VALUES (23,'shipping delays','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (15,'poor quality products','open');
INSERT INTO Complaint(user_id,description,status) VALUES (1,'website crashes','open');
INSERT INTO Complaint(user_id,description,status) VALUES (13,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (6,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'broken links','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (8,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (38,'shipping delays','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (19,'poor quality products','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (13,'poor customer service','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (2,'unresponsive support','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (3,'shipping delays','open');
INSERT INTO Complaint(user_id,description,status) VALUES (30,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (1,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (15,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (26,'slow loading times','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (28,'website crashes','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (9,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (31,'unresponsive support','open');
INSERT INTO Complaint(user_id,description,status) VALUES (36,'shipping delays','open');
INSERT INTO Complaint(user_id,description,status) VALUES (25,'incorrect product descriptions','open');
INSERT INTO Complaint(user_id,description,status) VALUES (15,'shipping delays','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (16,'billing errors','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (16,'website crashes','open');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'spam emails','open');
INSERT INTO Complaint(user_id,description,status) VALUES (30,'slow loading times','open');
INSERT INTO Complaint(user_id,description,status) VALUES (24,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (29,'poor quality products','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (28,'incorrect product descriptions','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (30,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'incorrect product descriptions','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (32,'slow loading times','open');
INSERT INTO Complaint(user_id,description,status) VALUES (23,'incorrect product descriptions','open');
INSERT INTO Complaint(user_id,description,status) VALUES (3,'shipping delays','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (38,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (17,'unresponsive support','open');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (32,'website crashes','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (11,'broken links','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'broken links','closed');

-- FLAGS (admin)

INSERT INTO Flag(admin_id,review_id,reason) VALUES (32,28,'spam');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (16,64,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (16,45,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (2,53,'irrelevant');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (26,11,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (39,27,'spam');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (32,64,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (35,47,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (22,18,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (9,17,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (10,16,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (16,44,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (31,12,'irrelevant');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (29,46,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (26,57,'offensive content');

-- TAG

INSERT INTO Tag(tag_name) VALUES ('Fast Food');
INSERT INTO Tag(tag_name) VALUES ('Fine Dining');
INSERT INTO Tag(tag_name) VALUES ('Casual Dining');
INSERT INTO Tag(tag_name) VALUES ('Family Friendly');
INSERT INTO Tag(tag_name) VALUES ('Vegan Options');
INSERT INTO Tag(tag_name) VALUES ('Vegetarian Friendly');
INSERT INTO Tag(tag_name) VALUES ('Gluten Free Options');
INSERT INTO Tag(tag_name) VALUES ('Halal Certified');
INSERT INTO Tag(tag_name) VALUES ('Kosher Options');
INSERT INTO Tag(tag_name) VALUES ('Pet Friendly');
INSERT INTO Tag(tag_name) VALUES ('Outdoor Seating');
INSERT INTO Tag(tag_name) VALUES ('Waterfront Views');
INSERT INTO Tag(tag_name) VALUES ('Late Night Dining');
INSERT INTO Tag(tag_name) VALUES ('Breakfast Spot');
INSERT INTO Tag(tag_name) VALUES ('Brunch Favorite');
INSERT INTO Tag(tag_name) VALUES ('Lunch Specials');
INSERT INTO Tag(tag_name) VALUES ('Takeout Available');
INSERT INTO Tag(tag_name) VALUES ('Delivery Service');
INSERT INTO Tag(tag_name) VALUES ('Drive Thru');
INSERT INTO Tag(tag_name) VALUES ('Buffet Style');
INSERT INTO Tag(tag_name) VALUES ('All You Can Eat');
INSERT INTO Tag(tag_name) VALUES ('Farm to Table');
INSERT INTO Tag(tag_name) VALUES ('Organic Ingredients');
INSERT INTO Tag(tag_name) VALUES ('Locally Sourced');
INSERT INTO Tag(tag_name) VALUES ('Sustainable Practices');
INSERT INTO Tag(tag_name) VALUES ('Eco Friendly');
INSERT INTO Tag(tag_name) VALUES ('Trendy Atmosphere');
INSERT INTO Tag(tag_name) VALUES ('Romantic Setting');
INSERT INTO Tag(tag_name) VALUES ('Group Friendly');
INSERT INTO Tag(tag_name) VALUES ('Live Music');
INSERT INTO Tag(tag_name) VALUES ('Sports Bar');
INSERT INTO Tag(tag_name) VALUES ('Craft Cocktails');
INSERT INTO Tag(tag_name) VALUES ('Full Bar');
INSERT INTO Tag(tag_name) VALUES ('Coffee and Cafe');
INSERT INTO Tag(tag_name) VALUES ('Dessert Specialties');
INSERT INTO Tag(tag_name) VALUES ('Street Food Style');
INSERT INTO Tag(tag_name) VALUES ('Food Truck');
INSERT INTO Tag(tag_name) VALUES ('Fusion Cuisine');
INSERT INTO Tag(tag_name) VALUES ('International Flavors');
INSERT INTO Tag(tag_name) VALUES ('Chef Specials');

-- COMPANY-TAG BRIDGE TABLE

INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,9);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,3);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,22);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,32);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,37);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,34);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,26);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,36);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,6);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (29,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (33,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (30,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,27);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (22,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (22,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (21,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,2);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,37);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,34);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (26,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (40,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,4);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (10,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (6,30);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,31);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (31,39);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (13,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (40,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (37,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,36);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (23,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,21);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (1,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,39);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,3);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,21);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,22);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (17,36);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (31,16);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (10,31);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (23,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,22);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,37);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,32);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,26);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,9);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (1,6);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (24,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (17,27);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,30);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (4,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (24,2);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (29,4);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,15);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,4);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,12);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (23,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,30);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (1,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (31,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,12);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (37,15);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,16);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (10,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,5);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,21);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (24,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,39);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (6,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (22,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,27);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,34);
