USE DiningDucks;

-- USER

INSERT INTO User(name, email, role) VALUES ('Georgeanna Want','gwant0@reference.com','employee');
INSERT INTO User(name, email, role) VALUES ('Elianora Overlow','eoverlow1@bravesites.com','company');
INSERT INTO User(name, email, role) VALUES ('Bink Reams','breams2@wiley.com','employee');
INSERT INTO User(name, email, role) VALUES ('Gerladina Marrian','gmarrian3@fotki.com','employee');
INSERT INTO User(name, email, role) VALUES ('Grover Coatts','gcoatts4@merriam-webster.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Ame Khoter','akhoter5@soup.io','employee');
INSERT INTO User(name, email, role) VALUES ('Rebekkah Poppy','rpoppy6@plala.or.jp','employee');
INSERT INTO User(name, email, role) VALUES ('Correna Kondrat','ckondrat7@elegantthemes.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Lexi Blaisdell','lblaisdell8@technorati.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Fabe Grimsdith','fgrimsdith9@google.es','reviewer');
INSERT INTO User(name, email, role) VALUES ('Valry Livings','vlivingsa@ftc.gov','admin');
INSERT INTO User(name, email, role) VALUES ('Alexia O'' Culligan','aob@youtube.com','admin');
INSERT INTO User(name, email, role) VALUES ('Falito Hext','fhextc@eepurl.com','company');
INSERT INTO User(name, email, role) VALUES ('Randa Sprasen','rsprasend@abc.net.au','reviewer');
INSERT INTO User(name, email, role) VALUES ('Philippa Welchman','pwelchmane@altervista.org','reviewer');
INSERT INTO User(name, email, role) VALUES ('Don Worner','dwornerf@slashdot.org','reviewer');
INSERT INTO User(name, email, role) VALUES ('Glenn Lightfoot','glightfootg@360.cn','reviewer');
INSERT INTO User(name, email, role) VALUES ('Etienne Thicking','ethickingh@ebay.co.uk','reviewer');
INSERT INTO User(name, email, role) VALUES ('Catlaina Salvador','csalvadori@utexas.edu','company');
INSERT INTO User(name, email, role) VALUES ('Charisse Delong','cdelongj@stumbleupon.com','admin');
INSERT INTO User(name, email, role) VALUES ('Harlene Cain','hcaink@pinterest.com','company');
INSERT INTO User(name, email, role) VALUES ('Gloria Eicheler','geichelerl@goodreads.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('April Dumbrall','adumbrallm@intel.com','employee');
INSERT INTO User(name, email, role) VALUES ('Gilly Shivlin','gshivlinn@yale.edu','reviewer');
INSERT INTO User(name, email, role) VALUES ('Deb Aiton','daitono@cnn.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Susanne Normabell','snormabellp@issuu.com','employee');
INSERT INTO User(name, email, role) VALUES ('Otha Nettleship','onettleshipq@surveymonkey.com','employee');
INSERT INTO User(name, email, role) VALUES ('Neila Haselup','nhaselupr@soup.io','employee');
INSERT INTO User(name, email, role) VALUES ('Marni Stiff','mstiffs@altervista.org','reviewer');
INSERT INTO User(name, email, role) VALUES ('Arman Chatres','achatrest@unc.edu','admin');
INSERT INTO User(name, email, role) VALUES ('Christoph Yarmouth','cyarmouthu@github.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Lesly Hinz','lhinzv@bandcamp.com','admin');
INSERT INTO User(name, email, role) VALUES ('Jerome Lohan','jlohanw@newyorker.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Jacqui Lapthorne','jlapthornex@discovery.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Jeane Pays','jpaysy@posterous.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Taddeusz Garmon','tgarmonz@cdbaby.com','employee');
INSERT INTO User(name, email, role) VALUES ('Leonanie Steggles','lsteggles10@over-blog.com','admin');
INSERT INTO User(name, email, role) VALUES ('Petunia Bethell','pbethell11@dyndns.org','admin');
INSERT INTO User(name, email, role) VALUES ('Lona Sadat','lsadat12@huffingtonpost.com','reviewer');
INSERT INTO User(name, email, role) VALUES ('Deanna Rowcastle','drowcastle13@wisc.edu','company');

-- COMPANY

INSERT INTO Company(name) VALUES ('Midtown Bites');
INSERT INTO Company(name) VALUES ('Lighthouse Dining');
INSERT INTO Company(name) VALUES ('Oak Table');
INSERT INTO Company(name) VALUES ('Riverstone Dining');
INSERT INTO Company(name) VALUES ('Skyline Kitchen');
INSERT INTO Company(name) VALUES ('Maple & Main');
INSERT INTO Company(name) VALUES ('Morning Star Cafe');
INSERT INTO Company(name) VALUES ('Cedar Plate');
INSERT INTO Company(name) VALUES ('Amber Table');
INSERT INTO Company(name) VALUES ('Summit Table');
INSERT INTO Company(name) VALUES ('Stonebridge Grill');
INSERT INTO Company(name) VALUES ('Willow & Fork');
INSERT INTO Company(name) VALUES ('West End Grill');
INSERT INTO Company(name) VALUES ('Brick Oven House');
INSERT INTO Company(name) VALUES ('Urban Bite');
INSERT INTO Company(name) VALUES ('Coastal Spoon');
INSERT INTO Company(name) VALUES ('Cornerstone Cafe');
INSERT INTO Company(name) VALUES ('Lighthouse Dining');
INSERT INTO Company(name) VALUES ('Ironwood Kitchen');
INSERT INTO Company(name) VALUES ('Urban Bite');
INSERT INTO Company(name) VALUES ('Skyline Kitchen');
INSERT INTO Company(name) VALUES ('Eastwood Eats');
INSERT INTO Company(name) VALUES ('Crimson Fork');
INSERT INTO Company(name) VALUES ('Northwind Diner');
INSERT INTO Company(name) VALUES ('Oak Table');
INSERT INTO Company(name) VALUES ('Ironwood Kitchen');
INSERT INTO Company(name) VALUES ('Urban Bite');
INSERT INTO Company(name) VALUES ('Golden Hour Bistro');
INSERT INTO Company(name) VALUES ('Blue Harbor Grill');
INSERT INTO Company(name) VALUES ('Brick Oven House');
INSERT INTO Company(name) VALUES ('Dining Ducks');
INSERT INTO Company(name) VALUES ('Golden Fork');
INSERT INTO Company(name) VALUES ('Maple & Main');
INSERT INTO Company(name) VALUES ('Cornerstone Cafe');
INSERT INTO Company(name) VALUES ('Blue Harbor Grill');
INSERT INTO Company(name) VALUES ('Bluebird Dining');
INSERT INTO Company(name) VALUES ('Harbor & Hearth');
INSERT INTO Company(name) VALUES ('Velvet Plate');
INSERT INTO Company(name) VALUES ('Lighthouse Dining');
INSERT INTO Company(name) VALUES ('Harvest & Co');

-- RESTAURANT LOCATION

INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (13,'69916 Dixon Road','Santa Rosa de Lima','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (2,'3 Kings Plaza','Sarae','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (28,'9520 Cody Junction','Selouane','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (2,'17186 Leroy Point','Säffle','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (23,'61780 Myrtle Plaza','San Juan Ixcoy','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'7921 Homewood Alley','Ubon Ratchathani','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (22,'827 Vahlen Place','Göteborg','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (30,'21933 Dunning Street','Santo Domingo','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (21,'9 Norway Maple Drive','Boavista','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (9,'52897 Huxley Park','Матејче','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (4,'332 Ridgeview Court','Annecy','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (10,'6266 Granby Parkway','Jiefang','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (26,'25 Alpine Circle','Jazovo','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (13,'28250 Haas Terrace','San Carlos','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'85131 Spaight Street','Donja Mahala','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (27,'852 Evergreen Way','Zuoxi','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (7,'2 Division Place','Rustāq','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (16,'8282 Carey Place','Skoroszyce','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'6 Lunder Point','Huurch','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'991 Forest Drive','Jiangcun','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'39884 Prairieview Court','Paris 12','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (40,'27 Mayer Street','São João Nepomuceno','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (31,'21 Atwood Pass','Casa Branca','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'8 Starling Drive','Asprángeloi','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (5,'7834 Elmside Court','Luchingu','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'6766 Porter Place','Sale','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (16,'95108 Barby Drive','Kedungasem','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (7,'55722 Cherokee Avenue','Kaduseeng','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'45 Old Shore Trail','Jinshan','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (25,'58028 Carpenter Alley','Pirassununga','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (3,'235 Express Place','Bcharré','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (23,'9307 Hollow Ridge Place','Pecka','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (34,'4 Arizona Avenue','Olyka','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (32,'0397 Shoshone Point','Łąka Prudnicka','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'08562 Holmberg Circle','Trairi','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'631 Harbort Lane','Garzón','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (4,'6 Bayside Way','Zhangjiafang','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'2 Burrows Crossing','Alfeizerão','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (1,'76 Harbort Hill','El Nido','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'411 Old Shore Pass','Tengah','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'0 Pawling Trail','Houmt Souk','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'6881 Bartelt Junction','Norak','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (39,'5 Reindahl Drive','Yaosai','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'7427 East Alley','Okanagan','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (27,'223 Oak Terrace','Desa Baregbeg','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (6,'7692 Sommers Crossing','Shawnee Mission','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (18,'66 Sage Trail','Bintang','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'664 Goodland Park','Cidahu','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (23,'0708 Melrose Terrace','Strogino','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (37,'5 Northport Alley','Xiongchi','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (8,'84813 Mayfield Park','Kamárai','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (35,'42140 Clyde Gallagher Avenue','Kudusan','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (1,'7005 Cody Parkway','Pangalangan','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (16,'68 Cambridge Place','Wenshao','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (34,'758 Merchant Junction','Menzel Abderhaman','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (10,'9 Lyons Hill','Beishan','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (30,'3027 Bunker Hill Trail','Lagunas','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (25,'1510 Sauthoff Crossing','Nerópolis','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (20,'0469 Superior Street','Bečmen','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (30,'304 Fairfield Point','Velventós','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (4,'79381 Gulseth Point','Nuevo Arraiján','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (1,'54649 School Trail','Baisha','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (36,'8672 Nancy Drive','Ōkuchi','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (14,'270 Laurel Circle','Kabar Utara','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (22,'13 Holmberg Plaza','Lobuni','$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (36,'0 Eagle Crest Trail','Marigot','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (33,'07583 5th Circle','Tirtopuro','$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (10,'37965 Tomscot Drive','Rezh','$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (40,'046 Tony Pass','Dolna Banya','$$$$');
INSERT INTO RestaurantLocation(company_id,address,city,price_range) VALUES (17,'810 Brickson Park Avenue','Pescadería','$$$');

-- CATEGORY (food, service, etc.)

INSERT INTO Category(name) VALUES ('pay');
INSERT INTO Category(name) VALUES ('management');
INSERT INTO Category(name) VALUES ('work-life balance');
INSERT INTO Category(name) VALUES ('oveall');
INSERT INTO Category(name) VALUES ('food');
INSERT INTO Category(name) VALUES ('$$$');
INSERT INTO Category(name) VALUES ('service');

-- CUSTOMER REVIEW

INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (12,45,'The ambiance was fantastic.','2026-03-09');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (7,22,'food was mediocre.','2025-11-01');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (31,9,'Not worth the price','2025-05-24');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (18,54,'The ambiance was fantastic.','2026-03-25');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (25,11,'Great food and service!','2025-10-19');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (3,67,'Great food and service!','2025-07-29');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (39,28,'The ambiance was fantastic.','2024-05-29');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (6,35,'food was mediocre.','2024-11-10');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (14,60,'Not worth the price','2025-12-27');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (21,5,'Would definitely recommend this place!','2024-06-14');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (8,49,'Great food and service!','2025-09-11');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (33,17,'The ambiance was fantastic.','2026-03-02');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (2,63,'food was mediocre.','2025-10-31');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (27,14,'Not worth the price','2024-12-11');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (10,51,'food was mediocre.','2024-05-25');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (36,30,'Not worth the price','2026-03-30');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (5,44,'food was mediocre.','2025-09-26');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (19,8,'Great food and service!','2024-09-20');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (28,70,'food was mediocre.','2026-04-16');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (11,21,'food was mediocre.','2025-05-16');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (40,6,'Not worth the price','2025-12-12');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (16,58,'Great food and service!','2024-06-11');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (9,33,'Great food and service!','2025-03-03');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (34,12,'food was mediocre.','2024-05-31');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (1,64,'food was mediocre.','2024-08-31');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (23,19,'The ambiance was fantastic.','2025-12-31');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (15,47,'Great food and service!','2025-07-18');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (37,26,'Great food and service!','2025-06-20');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (4,39,'The ambiance was fantastic.','2025-03-31');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (30,2,'Would definitely recommend this place!','2025-04-14');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (13,55,'The ambiance was fantastic.','2026-03-28');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (24,16,'The ambiance was fantastic.','2024-06-13');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (32,41,'food was mediocre.','2024-11-10');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (20,68,'Great food and service!','2025-06-06');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (6,23,'The ambiance was fantastic.','2026-03-26');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (29,50,'Not worth the price','2025-03-21');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (17,7,'food was mediocre.','2024-07-21');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (38,34,'Great food and service!','2025-10-03');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (3,61,'food was mediocre.','2026-01-25');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (22,13,'Would definitely recommend this place!','2025-08-31');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (35,46,'Would definitely recommend this place!','2024-05-11');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (8,27,'Great food and service!','2025-12-25');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (14,59,'Great food and service!','2025-03-10');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (26,18,'The ambiance was fantastic.','2024-07-27');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (31,65,'Not worth the price','2024-05-16');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (5,24,'Not worth the price','2025-05-04');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (11,40,'food was mediocre.','2025-04-15');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (19,10,'Would definitely recommend this place!','2025-09-01');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (33,52,'Not worth the price','2024-12-26');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (2,37,'Great food and service!','2026-01-16');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (27,4,'The ambiance was fantastic.','2024-06-03');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (16,66,'The ambiance was fantastic.','2026-03-15');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (9,29,'Would definitely recommend this place!','2024-08-25');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (34,56,'food was mediocre.','2024-08-23');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (1,15,'Great food and service!','2024-10-28');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (23,48,'Great food and service!','2024-08-05');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (15,20,'Not worth the price','2025-05-20');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (37,62,'food was mediocre.','2025-09-10');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (4,31,'Not worth the price','2024-07-09');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (30,69,'Great food and service!','2026-01-12');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (13,43,'food was mediocre.','2024-04-02');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (24,1,'Great food and service!','2025-03-18');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (32,57,'Would definitely recommend this place!','2024-12-27');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (20,25,'The ambiance was fantastic.','2024-12-25');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (6,53,'Great food and service!','2025-10-19');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (29,36,'The ambiance was fantastic.','2024-04-06');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (17,42,'Great food and service!','2024-08-02');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (38,3,'Not worth the price','2025-06-30');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (3,38,'Not worth the price','2024-06-10');
INSERT INTO CustomerReview(user_id,location_id,review_text,review_date) VALUES (22,32,'The ambiance was fantastic.','2024-12-09');

-- REVIEW RATINGS (per category)

INSERT INTO Rating(review_id,category_id,score) VALUES (57,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (2,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (5,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (21,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (10,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (26,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (53,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (44,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (43,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (15,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (65,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (35,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (7,4,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,5,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (42,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (42,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (12,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (59,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (36,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (49,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,2,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (47,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (57,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (45,3,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (8,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,7,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (42,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (57,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (33,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (16,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,4,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (5,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (38,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (66,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (6,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (26,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (39,3,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (2,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (43,1,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (5,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (21,2,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (11,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (53,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (4,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (32,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,4,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (38,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (64,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (15,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (51,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,4,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (25,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,1,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (51,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (14,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (17,7,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,3,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (16,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (32,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (53,4,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (49,3,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (21,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (59,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,7,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (66,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (63,4,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (28,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (15,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (64,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (29,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (24,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (63,3,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (6,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (67,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (33,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (2,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (50,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (56,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (62,1,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (36,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (31,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,4,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (54,7,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (67,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (46,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (27,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,7,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (43,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (48,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (12,6,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (11,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (10,1,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (68,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (13,4,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (40,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (32,7,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (60,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (50,6,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (70,6,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (12,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (18,1,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (26,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (20,3,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (64,6,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (3,1,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (59,3,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,2,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,5,3);
INSERT INTO Rating(review_id,category_id,score) VALUES (14,2,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (38,5,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,3,5);
INSERT INTO Rating(review_id,category_id,score) VALUES (60,2,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (58,4,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (41,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (55,5,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (35,6,2);
INSERT INTO Rating(review_id,category_id,score) VALUES (44,1,4);
INSERT INTO Rating(review_id,category_id,score) VALUES (1,2,1);
INSERT INTO Rating(review_id,category_id,score) VALUES (22,2,2);

-- EMPLOYEE REVIEW

INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (22,10,'making my job easier.','2026-02-12');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (1,15,'The customers were patient and understanding','2025-09-02');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,54,'The customers were patient and understanding','2025-09-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,55,'I had a great time interacting with the customers and providing top-notch service.','2025-10-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (9,12,'The atmosphere was cozy and welcoming.','2025-07-25');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,10,'The food was delicious and the customers were very friendly.','2025-09-19');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,20,'The restaurant was busy but I managed to keep up with all the orders and requests.','2026-03-30');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,5,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-06-10');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (28,37,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2026-03-18');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,28,'I had a great time interacting with the customers and providing top-notch service.','2026-03-21');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,70,'I had a great time interacting with the customers and providing top-notch service.','2026-01-24');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (11,29,'The food was delicious and the customers were very friendly.','2025-09-11');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (14,26,'I had a great time interacting with the customers and providing top-notch service.','2025-09-04');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (29,24,'I received positive feedback from the customers about the food and service.','2025-06-20');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,22,'The atmosphere was cozy and welcoming.','2025-05-05');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (31,28,'The restaurant was busy but I managed to keep up with all the orders and requests.','2025-11-25');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (37,51,'The customers were patient and understanding','2026-03-18');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (29,59,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-10-30');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (32,7,'I received positive feedback from the customers about the food and service.','2025-09-03');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (26,68,'I received positive feedback from the customers about the food and service.','2026-02-18');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,19,'The service was excellent and the customers seemed to enjoy their meals.','2026-02-06');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,8,'The atmosphere was cozy and welcoming.','2025-08-19');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (21,11,'making my job easier.','2026-03-02');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (28,47,'The customers were patient and understanding','2025-12-15');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,31,'I had a great time interacting with the customers and providing top-notch service.','2026-03-11');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,47,'The food was delicious and the customers were very friendly.','2026-01-23');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (23,24,'I felt proud of the quality of service I was able to deliver to the customers.','2025-11-09');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,32,'The service was excellent and the customers seemed to enjoy their meals.','2025-05-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (7,52,'I felt proud of the quality of service I was able to deliver to the customers.','2026-03-28');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,26,'The service was excellent and the customers seemed to enjoy their meals.','2025-05-06');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,27,'The customers were appreciative of the recommendations I provided for their meals.','2026-03-09');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,56,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-06-04');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,18,'I felt proud of the quality of service I was able to deliver to the customers.','2025-08-19');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,53,'I felt proud of the quality of service I was able to deliver to the customers.','2025-07-02');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,65,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-10-09');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (16,43,'The service was excellent and the customers seemed to enjoy their meals.','2025-06-04');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (15,21,'I had a great time interacting with the customers and providing top-notch service.','2025-12-06');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (23,11,'The atmosphere was cozy and welcoming.','2025-08-04');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,51,'making my job easier.','2025-05-16');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,13,'I felt proud of the quality of service I was able to deliver to the customers.','2025-07-14');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (27,40,'The service was excellent and the customers seemed to enjoy their meals.','2026-01-28');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (14,55,'The atmosphere was cozy and welcoming.','2025-12-15');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (5,7,'I felt proud of the quality of service I was able to deliver to the customers.','2026-01-14');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (32,6,'making my job easier.','2026-01-10');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (7,33,'I had a great time interacting with the customers and providing top-notch service.','2025-12-14');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (1,44,'The customers were patient and understanding','2026-04-06');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (24,70,'I received positive feedback from the customers about the food and service.','2026-03-21');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (26,43,'I received positive feedback from the customers about the food and service.','2025-08-09');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,38,'The customers were appreciative of the recommendations I provided for their meals.','2026-01-28');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,46,'The restaurant was busy but I managed to keep up with all the orders and requests.','2025-08-08');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,70,'The restaurant was busy but I managed to keep up with all the orders and requests.','2025-05-21');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (24,20,'The service was excellent and the customers seemed to enjoy their meals.','2025-11-27');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (12,57,'The customers were patient and understanding','2025-12-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (5,30,'The atmosphere was cozy and welcoming.','2025-12-08');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (4,61,'I received positive feedback from the customers about the food and service.','2025-05-30');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,63,'The customers were patient and understanding','2025-10-15');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (15,49,'The customers were patient and understanding','2026-02-14');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (1,15,'The service was excellent and the customers seemed to enjoy their meals.','2025-07-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,45,'The restaurant was busy but I managed to keep up with all the orders and requests.','2025-08-31');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,5,'The customers were patient and understanding','2025-07-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,47,'The atmosphere was cozy and welcoming.','2025-12-21');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (16,15,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-06-13');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,5,'The atmosphere was cozy and welcoming.','2026-01-07');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,25,'The atmosphere was cozy and welcoming.','2026-02-16');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (13,59,'The service was excellent and the customers seemed to enjoy their meals.','2026-02-17');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,32,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2026-03-09');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,27,'The customers were patient and understanding','2025-12-18');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (22,53,'The restaurant was busy but I managed to keep up with all the orders and requests.','2026-03-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,47,'making my job easier.','2026-01-24');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (17,29,'I received positive feedback from the customers about the food and service.','2025-07-19');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (13,66,'The atmosphere was cozy and welcoming.','2026-02-02');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,31,'I received positive feedback from the customers about the food and service.','2026-03-21');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,61,'I had a great time interacting with the customers and providing top-notch service.','2026-03-30');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,24,'I felt proud of the quality of service I was able to deliver to the customers.','2025-11-08');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (10,21,'I felt proud of the quality of service I was able to deliver to the customers.','2025-08-29');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (5,13,'I received positive feedback from the customers about the food and service.','2025-05-27');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,5,'making my job easier.','2025-09-17');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,66,'The atmosphere was cozy and welcoming.','2025-12-28');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (21,17,'The customers were patient and understanding','2026-03-06');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,27,'making my job easier.','2025-12-11');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (26,40,'I felt proud of the quality of service I was able to deliver to the customers.','2026-03-09');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (25,46,'making my job easier.','2025-07-24');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,33,'The atmosphere was cozy and welcoming.','2026-03-16');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,42,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2026-01-09');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (27,36,'The customers were appreciative of the recommendations I provided for their meals.','2025-06-11');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (13,22,'I had a great time interacting with the customers and providing top-notch service.','2026-01-06');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,18,'The customers were appreciative of the recommendations I provided for their meals.','2025-11-03');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (36,22,'I received positive feedback from the customers about the food and service.','2026-02-27');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,46,'making my job easier.','2026-01-05');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,18,'The food was delicious and the customers were very friendly.','2025-11-08');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (3,49,'I received positive feedback from the customers about the food and service.','2025-06-26');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (11,38,'making my job easier.','2026-04-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (11,36,'The atmosphere was cozy and welcoming.','2026-02-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,9,'I had a great time interacting with the customers and providing top-notch service.','2026-02-11');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (2,61,'I felt proud of the quality of service I was able to deliver to the customers.','2025-09-28');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,66,'I received positive feedback from the customers about the food and service.','2025-05-06');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (25,54,'The customers were appreciative of the recommendations I provided for their meals.','2026-03-13');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,2,'I received positive feedback from the customers about the food and service.','2026-01-12');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (8,58,'making my job easier.','2026-03-11');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (25,37,'The customers were patient and understanding','2025-08-26');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (6,9,'The customers were appreciative of the recommendations I provided for their meals.','2025-05-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (37,4,'making my job easier.','2026-03-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (40,26,'The customers were patient and understanding','2025-08-07');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,52,'I received positive feedback from the customers about the food and service.','2025-04-19');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (23,7,'The customers were patient and understanding','2026-01-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,31,'I felt proud of the quality of service I was able to deliver to the customers.','2026-04-10');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (15,54,'making my job easier.','2025-12-16');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (16,10,'The restaurant was busy but I managed to keep up with all the orders and requests.','2025-12-08');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (20,69,'The service was excellent and the customers seemed to enjoy their meals.','2025-08-26');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,54,'I had a great time interacting with the customers and providing top-notch service.','2025-11-02');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (37,10,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-08-12');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (32,11,'making my job easier.','2025-11-07');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (24,15,'I received positive feedback from the customers about the food and service.','2025-09-10');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,23,'making my job easier.','2025-07-10');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (34,51,'I felt proud of the quality of service I was able to deliver to the customers.','2025-09-05');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,11,'The customers were appreciative of the recommendations I provided for their meals.','2025-11-29');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,4,'The atmosphere was cozy and welcoming.','2025-04-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (3,13,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-10-18');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,12,'The service was excellent and the customers seemed to enjoy their meals.','2025-08-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (18,50,'The customers were appreciative of the recommendations I provided for their meals.','2025-11-10');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (6,28,'The restaurant was busy but I managed to keep up with all the orders and requests.','2025-12-28');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (22,50,'I enjoyed working with my team to ensure a smooth dining experience for the customers.','2025-10-22');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (29,62,'The atmosphere was cozy and welcoming.','2025-09-23');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (38,45,'I felt proud of the quality of service I was able to deliver to the customers.','2026-01-23');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (39,65,'The food was delicious and the customers were very friendly.','2026-04-01');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (39,13,'The customers were appreciative of the recommendations I provided for their meals.','2025-07-11');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (30,67,'The food was delicious and the customers were very friendly.','2026-02-02');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (12,25,'The customers were appreciative of the recommendations I provided for their meals.','2025-12-20');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (33,47,'I had a great time interacting with the customers and providing top-notch service.','2025-11-19');
INSERT INTO EmployeeReview(user_id,location_id,review_text,review_date) VALUES (7,16,'I received positive feedback from the customers about the food and service.','2025-06-15');

-- EMPLOYEE RATINGS
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (10,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (8,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (96,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (52,6,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (68,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (75,6,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (37,7,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (22,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (80,4,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (17,4,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (53,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (94,7,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (86,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (33,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (66,3,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (100,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (83,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (127,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (31,5,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (48,1,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (57,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (89,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (19,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (62,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (3,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (77,3,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (104,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (40,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (106,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (2,7,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (27,1,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (73,4,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (108,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (121,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (15,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (91,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (50,7,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (61,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (81,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (51,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (98,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (35,2,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (93,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (99,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (39,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (120,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (42,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (88,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (82,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (60,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (43,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (122,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (23,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (63,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (110,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (24,6,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (101,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (41,3,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (64,7,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (125,3,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (102,3,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (129,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (56,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (67,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (74,6,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (107,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (111,6,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (79,5,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (9,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (25,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (47,3,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (38,5,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (128,4,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (11,4,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (85,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (16,2,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (69,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (59,7,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (6,6,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (34,6,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (109,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (45,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (46,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (13,3,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (49,4,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (113,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (123,5,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (105,1,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (112,5,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (20,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (97,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (44,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (116,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (103,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (21,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (1,7,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (36,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (117,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (58,4,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (126,3,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (54,1,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (119,6,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (90,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (84,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (92,5,5);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (26,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (72,7,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (114,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (78,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (65,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (30,7,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (28,4,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (118,7,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (4,2,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (5,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (55,3,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (76,1,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (12,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (70,2,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (115,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (124,6,2);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (87,7,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (14,3,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (95,2,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (18,5,1);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (130,3,4);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (32,5,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (71,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (7,1,3);
INSERT INTO EmployeeRating(emp_review_id,category_id,score) VALUES (29,6,2);

-- PHOTOS

INSERT INTO Photo(location_id,url) VALUES (16,'http://dummyimage.com/225x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/131x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (18,'http://dummyimage.com/146x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (63,'http://dummyimage.com/179x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (46,'http://dummyimage.com/138x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (20,'http://dummyimage.com/220x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/238x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (57,'http://dummyimage.com/241x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (59,'http://dummyimage.com/212x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (40,'http://dummyimage.com/136x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (2,'http://dummyimage.com/207x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (17,'http://dummyimage.com/207x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (5,'http://dummyimage.com/153x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/148x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (62,'http://dummyimage.com/208x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (10,'http://dummyimage.com/189x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (31,'http://dummyimage.com/107x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (59,'http://dummyimage.com/193x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (29,'http://dummyimage.com/102x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (45,'http://dummyimage.com/218x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (51,'http://dummyimage.com/197x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (29,'http://dummyimage.com/100x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (1,'http://dummyimage.com/223x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (43,'http://dummyimage.com/204x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (70,'http://dummyimage.com/198x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (43,'http://dummyimage.com/212x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (27,'http://dummyimage.com/183x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (26,'http://dummyimage.com/172x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (63,'http://dummyimage.com/127x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (42,'http://dummyimage.com/197x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (27,'http://dummyimage.com/192x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (41,'http://dummyimage.com/134x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (42,'http://dummyimage.com/120x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (48,'http://dummyimage.com/186x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (46,'http://dummyimage.com/234x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (43,'http://dummyimage.com/121x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (63,'http://dummyimage.com/173x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (14,'http://dummyimage.com/179x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (17,'http://dummyimage.com/139x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (25,'http://dummyimage.com/129x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (53,'http://dummyimage.com/138x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (26,'http://dummyimage.com/155x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (36,'http://dummyimage.com/233x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (57,'http://dummyimage.com/226x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (38,'http://dummyimage.com/192x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (15,'http://dummyimage.com/227x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (35,'http://dummyimage.com/242x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (57,'http://dummyimage.com/160x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (6,'http://dummyimage.com/162x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (13,'http://dummyimage.com/112x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (1,'http://dummyimage.com/222x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (23,'http://dummyimage.com/149x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (4,'http://dummyimage.com/204x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (49,'http://dummyimage.com/134x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (9,'http://dummyimage.com/226x100.png/cc0000/ffffff');
INSERT INTO Photo(location_id,url) VALUES (64,'http://dummyimage.com/237x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (44,'http://dummyimage.com/248x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (47,'http://dummyimage.com/123x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (51,'http://dummyimage.com/107x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (45,'http://dummyimage.com/164x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (44,'http://dummyimage.com/154x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (62,'http://dummyimage.com/198x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (62,'http://dummyimage.com/190x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (12,'http://dummyimage.com/101x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (3,'http://dummyimage.com/107x100.png/dddddd/000000');
INSERT INTO Photo(location_id,url) VALUES (4,'http://dummyimage.com/140x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (42,'http://dummyimage.com/123x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (13,'http://dummyimage.com/215x100.png/ff4444/ffffff');
INSERT INTO Photo(location_id,url) VALUES (28,'http://dummyimage.com/146x100.png/5fa2dd/ffffff');
INSERT INTO Photo(location_id,url) VALUES (15,'http://dummyimage.com/242x100.png/cc0000/ffffff');

-- COMPLAINTS (For admin, help desk)

INSERT INTO Complaint(user_id,description,status) VALUES (13,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (11,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (33,'slow loading times','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (32,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (23,'poor customer service','open');
INSERT INTO Complaint(user_id,description,status) VALUES (9,'poor quality products','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (5,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (6,'poor quality products','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (36,'incorrect product descriptions','open');
INSERT INTO Complaint(user_id,description,status) VALUES (24,'poor quality products','open');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'website crashes','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (27,'poor quality products','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'poor customer service','open');
INSERT INTO Complaint(user_id,description,status) VALUES (11,'website crashes','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (24,'unresponsive support','open');
INSERT INTO Complaint(user_id,description,status) VALUES (22,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (1,'poor customer service','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (16,'slow loading times','open');
INSERT INTO Complaint(user_id,description,status) VALUES (23,'shipping delays','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (15,'poor quality products','open');
INSERT INTO Complaint(user_id,description,status) VALUES (1,'website crashes','open');
INSERT INTO Complaint(user_id,description,status) VALUES (13,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (6,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'broken links','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (8,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (38,'shipping delays','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (19,'poor quality products','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (13,'poor customer service','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (2,'unresponsive support','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (3,'shipping delays','open');
INSERT INTO Complaint(user_id,description,status) VALUES (30,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (1,'broken links','open');
INSERT INTO Complaint(user_id,description,status) VALUES (15,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (26,'slow loading times','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (28,'website crashes','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (9,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (31,'unresponsive support','open');
INSERT INTO Complaint(user_id,description,status) VALUES (36,'shipping delays','open');
INSERT INTO Complaint(user_id,description,status) VALUES (25,'incorrect product descriptions','open');
INSERT INTO Complaint(user_id,description,status) VALUES (15,'shipping delays','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (16,'billing errors','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (16,'website crashes','open');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'spam emails','open');
INSERT INTO Complaint(user_id,description,status) VALUES (30,'slow loading times','open');
INSERT INTO Complaint(user_id,description,status) VALUES (24,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (29,'poor quality products','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (28,'incorrect product descriptions','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (30,'billing errors','open');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'incorrect product descriptions','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (32,'slow loading times','open');
INSERT INTO Complaint(user_id,description,status) VALUES (23,'incorrect product descriptions','open');
INSERT INTO Complaint(user_id,description,status) VALUES (3,'shipping delays','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (38,'billing errors','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (17,'unresponsive support','open');
INSERT INTO Complaint(user_id,description,status) VALUES (4,'unresponsive support','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (32,'website crashes','closed');
INSERT INTO Complaint(user_id,description,status) VALUES (11,'broken links','pending');
INSERT INTO Complaint(user_id,description,status) VALUES (18,'broken links','closed');

-- FLAGS (admin)

INSERT INTO Flag(admin_id,review_id,reason) VALUES (32,28,'spam');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (16,64,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (16,45,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (2,53,'irrelevant');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (26,11,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (39,27,'spam');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (32,64,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (35,47,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (22,18,'inappropriate language');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (9,17,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (10,16,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (16,44,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (31,12,'irrelevant');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (29,46,'offensive content');
INSERT INTO Flag(admin_id,review_id,reason) VALUES (26,57,'offensive content');

-- TAG

INSERT INTO Tag(tag_name) VALUES ('Fast Food');
INSERT INTO Tag(tag_name) VALUES ('Fine Dining');
INSERT INTO Tag(tag_name) VALUES ('Casual Dining');
INSERT INTO Tag(tag_name) VALUES ('Family Friendly');
INSERT INTO Tag(tag_name) VALUES ('Vegan Options');
INSERT INTO Tag(tag_name) VALUES ('Vegetarian Friendly');
INSERT INTO Tag(tag_name) VALUES ('Gluten Free Options');
INSERT INTO Tag(tag_name) VALUES ('Halal Certified');
INSERT INTO Tag(tag_name) VALUES ('Kosher Options');
INSERT INTO Tag(tag_name) VALUES ('Pet Friendly');
INSERT INTO Tag(tag_name) VALUES ('Outdoor Seating');
INSERT INTO Tag(tag_name) VALUES ('Waterfront Views');
INSERT INTO Tag(tag_name) VALUES ('Late Night Dining');
INSERT INTO Tag(tag_name) VALUES ('Breakfast Spot');
INSERT INTO Tag(tag_name) VALUES ('Brunch Favorite');
INSERT INTO Tag(tag_name) VALUES ('Lunch Specials');
INSERT INTO Tag(tag_name) VALUES ('Takeout Available');
INSERT INTO Tag(tag_name) VALUES ('Delivery Service');
INSERT INTO Tag(tag_name) VALUES ('Drive Thru');
INSERT INTO Tag(tag_name) VALUES ('Buffet Style');
INSERT INTO Tag(tag_name) VALUES ('All You Can Eat');
INSERT INTO Tag(tag_name) VALUES ('Farm to Table');
INSERT INTO Tag(tag_name) VALUES ('Organic Ingredients');
INSERT INTO Tag(tag_name) VALUES ('Locally Sourced');
INSERT INTO Tag(tag_name) VALUES ('Sustainable Practices');
INSERT INTO Tag(tag_name) VALUES ('Eco Friendly');
INSERT INTO Tag(tag_name) VALUES ('Trendy Atmosphere');
INSERT INTO Tag(tag_name) VALUES ('Romantic Setting');
INSERT INTO Tag(tag_name) VALUES ('Group Friendly');
INSERT INTO Tag(tag_name) VALUES ('Live Music');
INSERT INTO Tag(tag_name) VALUES ('Sports Bar');
INSERT INTO Tag(tag_name) VALUES ('Craft Cocktails');
INSERT INTO Tag(tag_name) VALUES ('Full Bar');
INSERT INTO Tag(tag_name) VALUES ('Coffee and Cafe');
INSERT INTO Tag(tag_name) VALUES ('Dessert Specialties');
INSERT INTO Tag(tag_name) VALUES ('Street Food Style');
INSERT INTO Tag(tag_name) VALUES ('Food Truck');
INSERT INTO Tag(tag_name) VALUES ('Fusion Cuisine');
INSERT INTO Tag(tag_name) VALUES ('International Flavors');
INSERT INTO Tag(tag_name) VALUES ('Chef Specials');

-- COMPANY-TAG BRIDGE TABLE

INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,9);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,3);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,22);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,32);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,37);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,34);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,26);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,36);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,6);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (29,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (33,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (30,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,27);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (22,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (22,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (21,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,2);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,37);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,34);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (26,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (40,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,4);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (10,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (6,30);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,31);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (31,39);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (13,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (40,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (37,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,36);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (23,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,21);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (1,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,13);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (19,17);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,39);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,3);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,21);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,22);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (17,36);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (31,16);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (10,31);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (23,40);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (34,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,22);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,37);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,32);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,20);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,26);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (27,9);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (1,6);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (24,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (17,27);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,30);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (4,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (24,2);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (29,4);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (15,7);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,15);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (38,18);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,30);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (3,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,4);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (32,12);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (23,31);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,19);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (5,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (7,30);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,10);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (1,28);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (31,38);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (9,12);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (2,11);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (37,15);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (16,16);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (10,29);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (18,14);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,5);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,21);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (24,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,39);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (6,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (28,23);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (11,1);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (39,24);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (12,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (22,5);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (36,8);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (35,27);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (14,33);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (20,25);
INSERT INTO CompanyTag(company_id,tag_id) VALUES (25,34);
