USE DiningDucks;
TRUNCATE TABLE User;

insert into User (user_id, name, email, role) values (1, 'Rebe Donisi', 'rdonisi0@cbsnews.com', 'reviewer');
insert into User (user_id, name, email, role) values (2, 'Karin Hagland', 'khagland1@linkedin.com', 'reviewer');
insert into User (user_id, name, email, role) values (3, 'Zared Grinin', 'zgrinin2@sciencedirect.com', 'company');
insert into User (user_id, name, email, role) values (4, 'Marion Franklen', 'mfranklen3@hibu.com', 'reviewer');
insert into User (user_id, name, email, role) values (5, 'Ester Malecky', 'emalecky4@drupal.org', 'company');
insert into User (user_id, name, email, role) values (6, 'Leonanie Hans', 'lhans5@redcross.org', 'reviewer');
insert into User (user_id, name, email, role) values (7, 'Walker Tiffany', 'wtiffany6@booking.com', 'admin');
insert into User (user_id, name, email, role) values (8, 'Lucienne Grim', 'lgrim7@ted.com', 'employee');
insert into User (user_id, name, email, role) values (9, 'Debee Brothwood', 'dbrothwood8@house.gov', 'reviewer');
insert into User (user_id, name, email, role) values (10, 'Simonette Coslitt', 'scoslitt9@whitehouse.gov', 'admin');
insert into User (user_id, name, email, role) values (11, 'Lorenzo Wincer', 'lwincera@gizmodo.com', 'company');
insert into User (user_id, name, email, role) values (12, 'Baron Hoggins', 'bhogginsb@studiopress.com', 'reviewer');
insert into User (user_id, name, email, role) values (13, 'Salmon Mackriell', 'smackriellc@dmoz.org', 'employee');
insert into User (user_id, name, email, role) values (14, 'Nada Baline', 'nbalined@army.mil', 'reviewer');
insert into User (user_id, name, email, role) values (15, 'Justus Manderson', 'jmandersone@friendfeed.com', 'employee');
insert into User (user_id, name, email, role) values (16, 'Avery Hulme', 'ahulmef@amazon.co.jp', 'company');
insert into User (user_id, name, email, role) values (17, 'Adriaens Sorby', 'asorbyg@chicagotribune.com', 'employee');
insert into User (user_id, name, email, role) values (18, 'Cacilia Swadon', 'cswadonh@businessweek.com', 'reviewer');
insert into User (user_id, name, email, role) values (19, 'Carlita Vuitton', 'cvuittoni@earthlink.net', 'reviewer');
insert into User (user_id, name, email, role) values (20, 'Miran Panketh', 'mpankethj@ning.com', 'reviewer');
insert into User (user_id, name, email, role) values (21, 'Rickert Lambregts', 'rlambregtsk@de.vu', 'employee');
insert into User (user_id, name, email, role) values (22, 'Shanda Muneely', 'smuneelyl@arizona.edu', 'reviewer');
insert into User (user_id, name, email, role) values (23, 'Salaidh Mattack', 'smattackm@ibm.com', 'reviewer');
insert into User (user_id, name, email, role) values (24, 'Blair Vidineev', 'bvidineevn@storify.com', 'reviewer');
insert into User (user_id, name, email, role) values (25, 'Isabelita Naisbitt', 'inaisbitto@nps.gov', 'reviewer');
insert into User (user_id, name, email, role) values (26, 'Parker Candlish', 'pcandlishp@domainmarket.com', 'admin');
insert into User (user_id, name, email, role) values (27, 'Darin Marieton', 'dmarietonq@utexas.edu', 'company');
insert into User (user_id, name, email, role) values (28, 'Dwain Peto', 'dpetor@pen.io', 'reviewer');
insert into User (user_id, name, email, role) values (29, 'Ludovico Scorrer', 'lscorrers@diigo.com', 'employee');
insert into User (user_id, name, email, role) values (30, 'Gloria Rollins', 'grollinst@google.co.uk', 'admin');
insert into User (user_id, name, email, role) values (31, 'Alta Jenkerson', 'ajenkersonu@unesco.org', 'reviewer');
insert into User (user_id, name, email, role) values (32, 'Harley Durman', 'hdurmanv@com.com', 'admin');
insert into User (user_id, name, email, role) values (33, 'Ambrosi Criag', 'acriagw@seattletimes.com', 'employee');
insert into User (user_id, name, email, role) values (34, 'Gustavo Lorain', 'glorainx@usgs.gov', 'reviewer');
insert into User (user_id, name, email, role) values (35, 'Elissa Farfoot', 'efarfooty@ibm.com', 'reviewer');
insert into User (user_id, name, email, role) values (36, 'Cordell Pauli', 'cpauliz@jigsy.com', 'employee');
insert into User (user_id, name, email, role) values (37, 'Raddy Hattersley', 'rhattersley10@soup.io', 'admin');
insert into User (user_id, name, email, role) values (38, 'Veradis Corrado', 'vcorrado11@washington.edu', 'admin');
insert into User (user_id, name, email, role) values (39, 'Jerrome Harnwell', 'jharnwell12@pcworld.com', 'admin');
insert into User (user_id, name, email, role) values (40, 'Johnathon Pentecost', 'jpentecost13@wix.com', 'employee');

